---
- name: Clean and create logs dir 
  file: path={{ logs_dir | default(ansible_env.HOME) }}/logs/ state={{ item }}
  with_items:
      - absent
      - directory

- name: Set component configuration file path
  set_fact: component_config_file="{{ component.path + '/' + component.config_file_name }}"
  when: component.path and component.config_file_name

- name: Load component configuration
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ component_config_file }}"
      - "component.cfg"
      - "/etc/component.cfg"
  register: result
