---
- name: Remove and create logs dir
  file:
    path: "{{ logs_dir | default(ansible_env.HOME) }}/logs/ state={{ item }}"
    mode: 0644
  with_items:
    - absent
    - directory
  ignore_errors: true

# Load octario vars only when they were not passed already,
# so they are not overriden
- name: Load octario configuration
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ playbook_dir }}/../octario.yml"
    - "{{ inventory_dir }}/octario.yml"
    - "/etc/octario.yml"
  when: component is not defined
  ignore_errors: true

# To copy the component to remote host
- name: Install rsync
  become: yes
  retries: 3
  delay: 10
  yum:
    name='rsync'
    state=present
  register: task_result
  until: task_result is success

- name: Copy component to remote host
  synchronize:
    src: "{{ item }}/"
    dest: "{{ ansible_env.HOME }}/{{ component.name }}"
    use_ssh_args: yes
    # keep rsync quiet as we don't want console noise
    rsync_opts:
      - "--quiet"
      - "--exclude=.tox"
      - "--force"
      - "--delete"
  with_first_found:
    - "{{ component.path | default(omit) }}"
    - "{{ test.dir  | default(omit) }}"
    - "{% if lookup('env','WORKSPACE') %}{{ lookup('env','WORKSPACE') }}/{{ component.name }}
      {% else %}{{ omit }}{% endif %}"
    - "{{ inventory_dir }}/{{ component.name }}"
    - "{{ inventory_dir }}/../{{ component.name }}"
    - "{{ playbook_dir }}/../{{ component.name }}"
    - "{{ hostvars['localhost']['test']['dir'] }}"

# This is optional since not every component must have common configuration across all releases
- name: Load component common configuration
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
        - "{{ playbook_dir }}/../components_config/common/{{ component.name }}.yml"
        - "{{ inventory_dir }}/components_config/common/{{ component.name }}.yml"
      skip: true

- name: Load component configuration by specific release
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ playbook_dir }}/../components_config/{{ component.version |
      default(rhos_default_version) }}/{{ component.name }}/component.yml"
    - "{{ inventory_dir }}/components_config/{{ component.version |
      default(rhos_default_version) }}/{{ component.name }}/component.yml"
    - "{{ component.path | default(inventory_dir + '/' + component.name) }}/{{ component.config_file_name |
      default(config_file_name) }}"
    - "{{ playbook_dir }}/../component.yml"
    - "{{ inventory_dir }}/component.yml"
    - "/etc/component.yml"
    - "{{ component.path | default(inventory_dir + '/' + component.name) }}/jenkins-config.yml"
    - "{{ playbook_dir }}/../jenkins-config.yml"
    - "{{ inventory_dir }}/jenkins-config.yml"
    - "{{ inventory_dir }}/../{{ component.name }}/jenkins-config.yml"
    - "{{ playbook_dir }}/../{{ component.name }}/jenkins-config.yml"
    - "/etc/jenkins-config.yml"

- name: Setup component configuration based on operating system
  set_fact:
    component_config="{{ test_config.virt[item] | default(omit) }}"
  with_items:
    - "default"
    - "{{ ansible_os_family }}-{{ ansible_distribution_version | int }}"
    - "{{ ansible_os_family }}-{{ ansible_distribution_version }}"

- name: Deploy global scripts
  copy:
      src: "{{ item }}"
      dest: /tmp/
      mode: 0755
  with_fileglob:
      - ../files/*

- name: Deploy component specific scripts
  copy:
      src: "{{ item }}"
      dest: /tmp/
      mode: 0755
  with_fileglob:
    - "{{ playbook_dir }}/../components_config/{{ component.version |
      default(rhos_default_version) }}/{{ component.name }}/scripts/*"
