---
- name: Run tests
  shell: |
    export PATH=$PATH:/usr/sbin
    set -euo pipefail
    {{ component_config.run }}
  args:
    chdir: "{{ ansible_env.HOME }}/{{ component.name }}"
    executable: "{{ default_shell }}"
