---
# This role runs the actual component tests based on the chosen tester

- name: Running tests
  shell: >
    export PATH=$PATH:/usr/sbin;
    {{ test_cfg.run.replace('\n', '') }}
  args:
    chdir: "{{ component_path }}"
    executable: /bin/bash
  register: test_run
  ignore_errors: true

- name: Print test run
  debug: var=test_run

- name: Copy test results to logs dir
  fetch: src="{{ component_path }}/{{ item }}"
         dest="{{ logs_dir | default(ansible_env.HOME) }}"
         flat=yes
  with_items: test_cfg.archive

- include: collect_results.yml
  when: tester.name != "pep8"

- name: Pass or fail the test
  fail: msg="The test run failed"
  when: test_run.rc != 0
