---
# This role runs the actual component tests based on the chosen tester

# 'ignore_errors' is true because test results evaultion isn't done here, but in
# 'collect_logs' role, in the last task.
# new line stripped from run command because Ansible unable to parser it that way.
- name: HACK - update kernel - HACK
  become: yes
  shell: "sudo yum update -y {{ kernel_rpm }}"

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=5 timeout=300
  sudo: false

- name: Running tests
  shell: >
    export PATH=$PATH:/usr/sbin;
    {{ component_config.run.replace('\n', '') }}
  args:
    chdir: "{{ ansible_env.HOME }}/{{ component.name }}"
    executable: "{{ default_shell }}"
  register: test_run
  ignore_errors: true
