---
# This role runs the actual component tests based on the chosen tester

# 'ignore_errors' is true because test results evaluation isn't done here, but in
# 'collect_logs' role, in the last task.
# new line stripped from run command because Ansible unable to parse it that way.

- name: Running tests
  shell: |
    set -xo pipefail
    export PATH=$PATH:/usr/sbin
    {
      {{ component_config.run.replace('\n', '') }}
    } 2>&1 | tee {{ componentinfo.name }}_{{ component.tox_target }}.log
  args:
    chdir: "{{ ansible_env.HOME }}/{{ componentinfo.name }}"
    executable: "{{ default_shell }}"
  register: test_run
  changed_when: false
  failed_when: false
