---
# This role runs the actual component tests based on the chosen tester

# 'ignore_errors' is true because test results evaluation isn't done here, but in
# 'collect_logs' role, in the last task.

- name: Running tests
  shell: |
    set -xo pipefail
    export PATH=$PATH:/usr/sbin
    {
      {{ component_config.run }}
    } 2>&1 | tee {{ tester.component.tox_target }}.log
  args:
    chdir: "{{ ansible_env.HOME }}/{{ component.name }}"
    executable: "{{ default_shell }}"
  register: test_run
  changed_when: false
  failed_when: false
