# Tempest
# -------

tempest_regex: tempest\.api\.volume|tempest\.scenario.*volume|tempest\.api\.compute

# Dist-git
# --------
component_dist_git_name: 'python-cinderclient'
component_dist_git_url: 'git://pkgs.devel.redhat.com/rpms/python-cinderclient'
