- name: Run testr init
  shell: "tempest/venv testr init"
  args:
    creates: "tempest/.testrepository"
  tags:
    - skip_ansible_lint

- name: Run component specific commands
  shell: "{{ component_config.run.replace('\n', '') }}"
  changed_when: true
  tags:
    - skip_ansible_lint

- name: lauch the tempest tests
  shell: tools/run-tests.sh manila_tempest_tests.tests.api
  args:
    chdir: "~/{{ tester.dir }}"
  ignore_errors: true

- name: Fetch Tempest results
  fetch:
    src=/home/stack/tempest/tempest.xml
    dest={{ lookup('env', 'PWD') }}/tempest.xml
    flat=yes

