- name: Run testr init
  shell: "{{ tempest_prefix }}testr init"
  args:
    creates: "tempest/.testrepository"
    chdir: tempest
  tags:
    - skip_ansible_lint

- name: Run component specific commands
  shell: "{{ component_config.run.replace('\n', '') }}"
  changed_when: true
  tags:
    - skip_ansible_lint
  # WIP measure, not to be merged
  ignore_errors: true

- name: Run Tempest
  shell: "{{ tempest_prefix }}./tools/run-tests.sh --parallel --concurrency={{ tempest_concurrency | default('4') }} {{ tempest_regex | default('') }} --skip-file ./skipfile"
  args:
    chdir: tempest
  ignore_errors: true
  tags:
    - skip_ansible_lint

- name: Fetch Tempest results
  fetch:
    src="{{ ansible_env.HOME }}/tempest/tempest.xml"
    dest="{{ lookup('env', 'PWD') }}/tempest.xml"
    flat=yes
