- name: Run testr init
  shell: "tempest/venv testr init"
  args:
    creates: "tempest/.testrepository"
  when: tempest_install_type == "git"
  tags:
    - skip_ansible_lint

- name: Run component specific commands
  shell: "{{ component_config.run.replace('\n', '') }}"
  changed_when: true
  tags:
    - skip_ansible_lint

- name: Run Tempest - git
  shell: "tempest/venv ./tools/run-tests.sh {{ tempest_regex | default('') }} --skip-file ./skipfile"
  ignore_errors: true
  when: tempest_install_type == "git"
  tags:
    - skip_ansible_lint

# The number of workers to use, defaults to the number
- name: Run Tempest - rpm
  shell: "ostestr -s --no-pretty --regex '{{ tempest_regex | default('') }}' ./skipfile | subunit2junitxml --output-to=tempest.xml | subunit2pyunit"
  ignore_errors: true
  args:
    chdir: tempest
  when: tempest_install_type == "rpm"
  tags:
    - skip_ansible_lint


- name: Fetch Tempest results
  fetch:
    src=/home/stack/tempest/tempest.xml
    dest={{ lookup('env', 'PWD') }}/tempest.xml
    flat=yes
