- name: Run testr init
  shell: |
    {{ tempest_venv_activate }}
    testr init
  args:
    creates: "{{ tempest_run_dir }}/.testrepository"
    chdir: "{{ tempest_run_dir }}"
  tags:
    - skip_ansible_lint

- name: Run component specific commands
  shell: "{{ component_config.run }}"
  args:
    chdir: "{{ component.name }}"
  changed_when: true
  tags:
    - skip_ansible_lint

- name: Run Tempest
  shell: |
    set -eo pipefail
    {{ tempest_venv_activate }}
    set -u
    ./tools/run-tests.sh --parallel {{ tempest_regex | default('') }} --skip-file ./skipfile | tee tempest.log | tail -n200
  # set -u should be after activate to avoid https://github.com/pypa/virtualenv/issues/150
  args:
    chdir: "{{ tempest_run_dir }}"
  ignore_errors: true
  tags:
    - skip_ansible_lint

- name: Fetch Tempest results
  fetch:
    src="{{ tempest_run_dir }}/{{ item }}"
    dest="{{ lookup('env', 'PWD') }}/{{ item }}"
    flat=yes
  with_items:
    - tempest.xml
    - tempest.log
