- name: Run testr init
  shell: "tempest/venv testr init"
  args:
    creates: "tempest/.testrepository"
  tags:
    - skip_ansible_lint

- name: Run component specific commands
  shell: "{{ component_config.run.replace('\n', '') }}"
  changed_when: true
  tags:
    - skip_ansible_lint

- name: Run Tempest
  shell: ostestr --concurrency 4 -r manila_tempest_tests.tests.api --subunit --no-pretty | subunit2junitxml > tempest.xml 
  ignore_errors: true
  tags:
    - skip_ansible_lint

- name: Fetch Tempest results
  fetch:
    src=/home/stack/tempest/tempest.xml
    dest={{ lookup('env', 'PWD') }}/tempest.xml
    flat=yes
