- name: Run testr init
  shell: "tempest/.venv testr init"
  args:
    creates: "tempest/.testrepository"

- name: Run component specific commands
  shell: "{{ component_config.run.replace('\n', '') }}"

- name: Run Tempest
  shell: >
    source tempest/.venv/bin/activate;
    tempest/tools/run-tests.sh --parallel --concurrency={{ tempest_concurrency | default('4') }} {{ tempest_regex | default('') }} --skip-file ./skipfile
  ignore_errors: true

- name: Fetch Tempest results
  fetch:
    src=/home/stack/tempest/tempest.xml
    dest={{ lookup('env', 'PWD') }}/tempest.xml
    flat=yes
