- name: Run testr init
  shell: "{{ tempest_prefix }}testr init"
  args:
    creates: "tempest/.testrepository"
    chdir: tempest
  tags:
    - skip_ansible_lint

- name: Run component specific commands
  shell: "{{ component_config.run }}"
  args:
    chdir: "{{ component.name }}"
  changed_when: true
  tags:
    - skip_ansible_lint

- name: Run Tempest
  shell:
    set -euo pipefail;
    {{ tempest_prefix }}./tools/run-tests.sh --parallel --concurrency={{ tempest_concurrency | default('4') }} {{ tempest_regex | default('') }} --skip-file ./skipfile | tee tempest.log | tail -n200
  args:
    chdir: tempest
  ignore_errors: true
  tags:
    - skip_ansible_lint

- name: Fetch Tempest results
  fetch:
    src="{{ ansible_env.HOME }}/tempest/{{ item }}"
    dest="{{ lookup('env', 'PWD') }}/{{ item }}"
    flat=yes
  with_items:
    - tempest.xml
    - tempest.log
