- name: Clone Red Hat Tempest repo
  git:
    repo="https://github.com/redhat-openstack/tempest.git"
    version='HEAD'
    dest="tempest"

- name: Install pip
  become: yes
  command: "easy_install pip"

- name: Install virtualenv
  become: yes
  become_method: sudo
  yum:
    name=python-virtualenv
    state=present

- name: Create venv with packages
  become: yes
  pip:
    virtualenv="tempest/.venv"
    name="{{ item }}"
    state=latest
  with_items:
    - pip
    - setuptools
    - pbr
    - junitxml
    - unittest2

- name: Install tempest requirements
  become: yes
  pip:
    virtualenv=".venv"
    chdir="tempest"
    requirements="{{ item }}"
  with_items:
    - requirements.txt
    - test-requirements.txt
