- name: Install needed RPMs for running tempest from git
  become: true
  become_method: sudo
  yum:
    name="{{ item }}"
    state=present
  with_items:
    - 'gcc'
    - 'libffi-devel'
    - 'openssl-devel'
    - 'python-unittest2'
    - 'python-junitxml'

- name: Clone Red Hat Tempest repo
  git:
    repo="https://github.com/redhat-openstack/tempest.git"
    version='HEAD'
    dest="{{ tempest_cwd }}"

- name: Install pip
  become: yes
  command: "easy_install pip"

- name: Install virtualenv
  become: yes
  become_method: sudo
  yum:
    name=python-virtualenv
    state=present

- name: Install tempest virtualenv
  shell: python tempest/tools/install_venv.py tempest
