- name: Install needed RPMs for running tempest from git
  become: true
  become_method: sudo
  yum:
    name="{{ item }}"
    state=present
  with_items:
    - 'gcc'
    - 'libffi-devel'
    - 'openssl-devel'

- name: Clone Red Hat Tempest repo
  git:
    repo="https://github.com/redhat-openstack/tempest.git"
    version="{{ rhos_upstream_map[component.version].release }}"
    dest="tempest"
