- name: Install needed RPMs for running tempest
  become: true
  yum:
    name="{{ item }}"
    state=present
  with_items:
    - 'subunit-filters'
    - 'python-junitxml'
    - 'python-neutronclient' # cli used in setup_tempest.sh.j2
    - 'python-novaclient' # cli used in setup_tempest.sh.j2

- name: Install per-component tempest test dependencies RPMs needed
  become: yes
  yum: pkg="{{ item }}" state=latest
  with_items: "{{ tempest.rpm_deps | default([]) }}"
  when: tempest | default(false) and tempest.rpm_deps | default(false)
  tags:
   - skip_ansible_lint

- include: "{{ tempest_install_type }}.yml"

- name: Copy keystonerc into overcloud_rc_file
  copy:
    src="{{ inventory_dir }}/keystonerc"
    dest="{{ overcloud_rc_file }}"
    mode=0644
  become: true
  ignore_errors: true

- name: Deploy tempest configuration script
  template:
    src=setup_tempest.sh.j2
    dest='tempest/setup_tempest.sh'
    mode=0755

- name: Configure tempest
  shell: ./setup_tempest.sh
  args:
    chdir: "{{ tempest_run_dir }}"
    # creates: "{{ tempest_run_dir }}/etc/tempest.conf"
  tags:
    - skip_ansible_lint

# If no skipfile is present, tempest will fail to run
- name: Create empty skip file
  file:
    path="{{ tempest_skipfile | default(overcloud_skipfile) }}"
    state=touch
    mode=0555

- name: create skip list - Whitelist
  lineinfile:
    create: yes
    dest: "{{ tempest_skipfile | default(overcloud_skipfile) }}"
    line: "+{{ item }}"
    regexp: "^[-+]{{ item }}$"
  with_items: "{{ tempest.whitelist | default([]) }}"

- name: create skip list - Blacklist
  lineinfile:
    create: yes
    dest: "{{ tempest_skipfile | default(overcloud_skipfile) }}"
    line: "-{{ item }}"
    regexp: "^[-+]{{ item }}$"
  with_items: "{{ tempest.blacklist | default([]) }}"
