- name: Install needed RPMs for running tempest
  become: true
  yum:
    name="{{ item }}"
    state=present
  with_items:
    - 'subunit-filters'
    - 'python-junitxml'
    - 'python-neutronclient'

- name: Install per-component tempest test dependencies RPMs needed
  become: yes
  yum: pkg="{{ item }}" state=latest
  with_items: "{{ tempest.rpm_deps | default([]) }}"
  when: tempest | default(false) and tempest.rpm_deps | default(false)

- include: "{{ tempest_install_type }}.yml"

- name: Copy keystonerc into overcloud_rc_file
  copy:
    src="{{ inventory_dir }}/keystonerc"
    dest="{{ overcloud_rc_file }}"
    mode=0644
  become: true

- name: run tempest configuration tool
  shell: |
      source {{ overcloud_rc_file }}

      # Discover number of overcloud compute nodes that are in Running power state
      # This is required by tempest migration tests
      #
      min_compute_nodes=$(nova list --name compute |grep Running|wc -l)

      # Use scheduler filters from nova.conf
      # By default "all" scheduler filters are used in Tempest which causes some
      # tests to fail.
      #
      nova_sched_filters=$(sudo sed -n '/^scheduler_default_filters=/p' /etc/nova/nova.conf | cut -f2 -d=)

      # Create external network
      # -----------------------
      public_net_id=$(neutron net-show ${pool_name:-public} -f value -c id)

      # Create external subnet
      # ---------------------
      neutron subnet-create \
        --name ext-subnet \
        --allocation-pool start=192.0.2.50,end=192.0.2.180 \
        --disable-dhcp --gateway 192.0.2.1 ${pool_name:-public} 192.0.2.0/24

      public_net_id=$(neutron net-show ${pool_name:-public} -f value -c id)

      {{ tempest_venv_activate }}
      ./tools/config_tempest.py --out etc/tempest.conf --network-id ${public_net_id} \
              --debug --create identity.uri $OS_AUTH_URL \
                identity.admin_password $OS_PASSWORD \
                object-storage.operator_role {% if component_version|int < 7 %}SwiftOperator{% else %}swiftoperator{% endif%} \
                orchestration.stack_owner_role heat_stack_owner \
                compute.min_compute_nodes ${min_compute_nodes:-0} \
                compute-feature-enabled.scheduler_available_filters "${nova_sched_filters:-RetryFilter,AvailabilityZoneFilter,RamFilter,ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,CoreFilter}"
  args:
      chdir: "{{ tempest_run_dir }}"
      creates: "{{ tempest_run_dir }}/etc/tempest.conf"

# If no skipfile is present, tempest will fail to run
- name: Create empty skip file
  file:
    path="{{ tempest_skipfile | default(overcloud_skipfile) }}"
    state=touch
    mode=0555

- name: create skip list - Whitelist
  lineinfile:
    create: yes
    dest: "{{ tempest_skipfile | default(overcloud_skipfile) }}"
    line: "+{{ item }}"
    regexp: "^[-+]{{ item }}$"
  with_items: "{{ tempest.whitelist | default([]) }}"

- name: create skip list - Blacklist
  lineinfile:
    create: yes
    dest: "{{ tempest_skipfile | default(overcloud_skipfile) }}"
    line: "-{{ item }}"
    regexp: "^[-+]{{ item }}$"
  with_items: "{{ tempest.blacklist | default([]) }}"
