- name: Install tempest RPM
  yum:
    name=openstack-tempest

- name: Install pip
  become: yes
  command: "easy_install pip"

- name: Install virtualenv
  become: yes
  become_method: sudo
  yum:
    name=python-virtualenv
    state=present

- name: Ensure tempest dir exists
  file: path=tempest state=directory
  
- name: Deploy 'venv' script to run tempest related commands inside virtualenv
  copy:
    src="venv"
    dest="tempest/venv"
    mode=0755
    