- name: Install tempest RPM
  become: true
  become_method: sudo
  yum: state=present name={{ item }}
  with_items:
     - subunit-filters
     - python-junitxml
     - python-tox
     - python-ddt
     - python-testscenarios
     - python-junitxml
     - subunit-filters
     - python-jsonschema
     - python-subunit
     - python-os-testr
     - openstack-tempest
     - openstack-tempest-all

- name: Ensure tempest dir exists
  file: path=tempest state=directory

- name: Configure tempest directory
  shell: /usr/share/openstack-tempest-13.0.0/tools/configure-tempest-directory 
  args:
    chdir: tempest
