- name: Install tempest RPM
  yum:
    name=openstack-tempest

- name: Ensure tempest dir exists
  file: path=tempest state=directory

- name: Configure tempest directory
  shell: /usr/share/openstack-tempest-13.0.0/tools/configure-tempest-directory 
  args:
    chdir: tempest
