- name: Install tempest RPM
  yum:
    name=openstack-tempest
    state=present
  become: yes

- name: Ensures ~/tempest dir exists
  file:
    path=tempest
    state=directory

- name: Get the script which configures the tempest directory
  shell: ls -d /usr/share/openstack-tempest-*/tools/configure-tempest-directory
  register: configure_tempest_dir
  ignore_errors: true

- name: Initialize tempest workspace directory
  command: "{{ configure_tempest_dir.stdout_lines[0] }}"
  args:
      chdir: "~/tempest"
      creates: "~/tempest/LICENSE"
  when: configure_tempest_dir.rc == 0

- name: Initialize tempest workspace directory using tempest init
  command: "tempest init"
  args:
      chdir: "~/tempest"
      creates: "~/tempest/etc"
  when: configure_tempest_dir.rc != 0

- set_fact:
    tempest_prefix: ""
