- name: Install tempest RPM
  become: true
  become_method: sudo
  yum: state=present name={{ item }}
  with_items:
     - subunit-filters
     - python-junitxml
     - python-tox
     - python-ddt
     - python-testscenarios
     - python-junitxml
     - subunit-filters
     - python-jsonschema
     - python-subunit
     - python-os-testr
     - openstack-tempest
     - openstack-tempest-all

- name: Clone Red Hat Tempest repo
  git:
    repo="https://github.com/redhat-openstack/tempest.git"
    version="{{ rhos_upstream_map[component.version].release }}"
    dest="/tmp/tempest"

- name: Ensure tempest dir exists
  file: path=tempest state=directory

- name: Copy files required to setup virtual env to run the tempest configuration
  copy: remote_src=True src=/tmp/tempest/{{ item }}  dest=tempest
  with_items:
    - test-requirements.txt
    - requirements.txt


- name: Get the script which configures the tempest directory
  shell: ls -d /usr/share/openstack-tempest-*/tools/configure-tempest-directory
  register: configure_tempest_dir
  ignore_errors: true

- name: Initialize tempest workspace directory
  command: "{{ configure_tempest_dir.stdout_lines[0] }}"
  args:
      chdir: "~/tempest"
      creates: "~/tempest/LICENSE"
  when: configure_tempest_dir.rc == 0

