- name: Install tempest RPM
  yum:
    name=openstack-tempest
    state=present
  become: yes

# we cannot use tempest from its location because it writes some files there
- name: fetch tempest from install location
  shell: "rsync -ah /usr/share/openstack-tempest-kilo/ {{ ansible_env.HOME }}/tempest/"
  args:
    warn: no

- set_fact:
    tempest_prefix: ""
