- name: Install dependencies required to run Tempest
  become: true
  yum: state=present name={{ item }}
  with_items:
     - python-tox
     - python-ddt
     - python-testscenarios
     - python-jsonschema
     - python-subunit
     - python-os-testr
     - openstack-tempest

# cannot be installed on rhos < 8 due to conflict
- name: Install optional Tempest dependencies (python-os-testr)
  vars:
     component_version: "{{ component.version | default(rhos_default_version) }}"
  become: true
  yum: state=present name=python-os-testr
  when: "component_version >= 8"

# this task is needed only for rhos_version==10
- name: Install optional Tempest dependencies (openstack-tempest-all)
  vars:
     component_version: "{{ component.version | default(rhos_default_version) }}"
  become: true
  yum: state=present name=openstack-tempest-all
  when: "component_version == 10"

- name: Install dependencies for filtering and collecting logs
  become: true
  yum: state=present name={{ item }}
  with_items:
     - subunit-filters
     - python-junitxml

- name: Create tmp dir
  shell: mktemp -d
  register: random_tmp_dir

- name: Create ~/tempest directory if not exists
  file:
    path="{{ tempest_cwd }}"
    state=directory

- name: Locate the script which configures the tempest directory
  shell: ls -d /usr/share/openstack-tempest-*/tools/configure-tempest-directory
  register: configure_tempest_dir
  ignore_errors: true

- name: Initialize tempest workspace directory
  command: "{{ configure_tempest_dir.stdout_lines[0] }}"
  args:
      chdir: "~/tempest"
      creates: "~/tempest/LICENSE"
  when: configure_tempest_dir.rc == 0
