- name: Install dependencies required to run Tempest
  become: true
  yum: state=present name={{ item }}
  with_items:
     - python-tox
     - python-ddt
     - python-testscenarios
     - python-jsonschema
     - python-subunit
     - openstack-tempest

- debug:
    msg: "{{ component_version }} : {{ rhos_default_version }}"

# cannot be installed on rhos < 8 due to conflict
- name: Install optional Tempest dependencies (python-os-testr)
  become: true
  yum: state=present name=python-os-testr
  when: "component_version|int > 7"

# this task is needed only for rhos_version==10
- name: Install optional Tempest dependencies (openstack-tempest-all)
  become: true
  yum: state=present name=openstack-tempest-all
  when: "component_version|int == 10"

- name: Install dependencies for filtering and collecting logs
  become: true
  yum: state=present name={{ item }}
  with_items:
     - subunit-filters
     - python-junitxml

- name: Create ~/tempest directory if not exists
  file:
    path="{{ tempest_run_dir }}"
    state=directory

- name: Locate the script which configures the tempest directory
  shell: ls -d /usr/share/openstack-tempest-*/tools/configure-tempest-directory
  register: configure_tempest_dir
  ignore_errors: true

- name: Initialize tempest workspace directory
  command: "{{ configure_tempest_dir.stdout_lines[0] }}"
  args:
      chdir: "~/tempest"
      creates: "~/tempest/LICENSE"
  when: configure_tempest_dir.rc == 0

- name: Install tempestconf if config script is not part of tempest
  become: yes
  package:
      name: python-tempestconf
      state: present
  when: configure_tempest_dir.rc != 0

# For RHOS 11 this step fails with error message:
# Could not load oslo.i18n, oslo.serialization, oslo.utils
# Follow the: https://bugzilla.redhat.com/show_bug.cgi?id=1429465
- name: Initialize tempest workspace directory using tempest init
  command: "tempest init"
  args:
      chdir: "{{ tempest_run_dir }}"
      creates: "{{ tempest_run_dir }}/etc"
  when: configure_tempest_dir.rc != 0

- name: Check if we have tempestconf tool installed
  stat:
      path: /usr/bin/discover-tempest-config
  register: tempest_conf_tool

- name: Set facts for configuration run
  set_fact:
      config_command: /usr/bin/discover-tempest-config
  when: tempest_conf_tool.stat.exists

