rhos_default_version: "{{ ansible_env.RHOS_VERSION | default(9) }}"
component_version: "{{ component.version | default(rhos_default_version) }}"
tempest_run_dir: '{{ ansible_env.HOME }}/tempest'
overcloud_rc_file: '{{ ansible_env.HOME }}/overcloudrc'
overcloud_venv: '{{ tempest_run_dir }}/.venv'
overcloud_skipfile: '{{ tempest_run_dir }}/skipfile'
tempest_venv_activate: |
    {% if tempest_install_type == 'git' %}
    if [[ -d '{{ overcloud_venv }}' ]]; then
        set +u
        source '{{ overcloud_venv}}/bin/activate'
        set -u
    fi
    {% endif %}
tempest_skipfile: "{{ tempest_run_dir }}/skipfile"