---
# This task will register all repos on the system to disable each one of them
# with the second task.
- name: Register all the repsitories
  shell: ls /etc/yum.repos.d/*
  register: yum_repos

- name: Disable any existing repos
  become: yes
  become_method: sudo
  replace:
    dest: "{{ item }}" 
    regexp: "enabled=1"
    replace: "enabled=0"
  with_items: "{{ yum_repos.stdout_lines }}" 

# This will install the repo that holds the test depedencies of the
# different projects
- name: Install the COPR test depedencies repo
  vars:
    component_version: "{{ component.version | default(stable_version) }}"
  become: yes
  become_method: sudo
  template: src=../templates/component-test-copr-repo.j2 dest=/etc/yum.repos.d/test-reqs-copr.repo

# rhos-release used for installing the right rhos repos.
# This depends on setting the right internal rhos-release server by 'export rhos_release_server=<the_server_ip_or_fqdn>'.
# If you are unfamiliar with the server address, please contact octario maintainers.
- name: Install rhos-release
  become: yes
  become_method: sudo
  vars:
    rhos_server: "{{ rhos_release_server | default(lookup('env','rhos_release_server')) }}"
  yum:
    name="http://{{ rhos_server }}/repos/rhos-release/rhos-release-latest.noarch.rpm"

- name: Execute rhos-release to install rhos repos
  vars:
    component_version: "{{ component.version | default(stable_version) }}"
  become: yes
  become_method: sudo
  shell: "rhos-release -x; rhos-release -d {{ component_version }}"
