---
# This task will register all repos on the system to disable each one of them
# with the second task.
- name: Register all the repositories
  shell: find /etc/yum.repos.d -name "*.repo"
  register: yum_repos
  changed_when: False

- name: Disable any existing repos
  become: yes
  become_method: sudo
  replace:
    dest: "{{ item }}"
    regexp: "enabled=1"
    replace: "enabled=0"
  with_items: "{{ yum_repos.stdout_lines | default() }}"

# rhos-release used for installing the rhos repos.
- name: Install rhos-release
  become: yes
  package:
    name="http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm"

- name: Execute rhos-release to install rhos repos
  vars:
    component_version: "{{ component.version | default(rhos_default_version) }}"
    component_version_director: "{{ (component_version|int in [7, 8, 9]) | ternary(component_version + '-director', '') }}"
  become: yes
  shell: |
    {{ rhos_release_bin }} -x
    sudo rhos-release 12 -d -p 2018-10-02.1
  args:
    warn: no
  changed_when: true
  tags:
    - skip_ansible_lint

- name: enable yum-config-manager
  package:
    name: yum-utils

# -test-deps are the COPR test deps.
# avoid use of yum_repository module because we would lose the ability
# to use rhos-release logic, like repo locations. We want to avoid maintenance.
- name: enable test repositories
  vars:
    component_version: "{{ component.version | default(rhos_default_version) }}"
  become: yes
  shell: |
    yum-config-manager \
      --enable rhelosp-{{ component_version }}.0-unittest \
      --enable rhelosp-{{ component_version }}.0-test-deps \
      >> /var/log/yum.log
  changed_when: true
