---
# This task will register all repos on the system to disable each one of them
# with the second task.
- name: Register all the repsitories
  shell: "{{ ls_bin }} /etc/yum.repos.d/*.repo"
  register: yum_repos

- name: Disable any existing repos
  become: yes
  become_method: sudo
  replace:
    dest: "{{ item }}"
    regexp: "enabled=1"
    replace: "enabled=0"
  with_items: "{{ yum_repos.stdout_lines }}"

# This will install the repo that holds the test depedencies of the
# different projects
- name: Install the COPR test depedencies repo
  vars:
    component_version: "{{ component.version | default(rhos_default_version) }}"
  become: yes
  become_method: sudo
  template: src=../templates/component-test-copr-repo.j2 dest=/etc/yum.repos.d/test-reqs-copr.repo

# rhos-release used for installing the rhos repos.
- name: Install rhos-release
  become: yes
  become_method: sudo
  yum:
    name="http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm"

- name: Execute rhos-release to install rhos repos
  vars:
    component_version: "{{ component.version | default(rhos_default_version) }}"
  become: yes
  become_method: sudo
  shell: "{{ rhos_release_bin }} -x; {{ rhos_release_bin }} -P -d {{ component_version }}"
