---
# This task will register all repos on the system to disable each one of them
# with the second task.
- name: Register all the repsitories
  shell: find /etc/yum.repos.d -name "*.repo"
  register: yum_repos
  changed_when: False

- name: Disable any existing repos
  become: yes
  become_method: sudo
  replace:
    dest: "{{ item }}"
    regexp: "enabled=1"
    replace: "enabled=0"
  with_items: "{{ yum_repos.stdout_lines | default() }}"

# rhos-release used for installing the rhos repos.
- name: Install rhos-release
  become: yes
  yum:
    name="http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm"

# -test-deps are the COPR test deps.
- name: Execute rhos-release to install rhos repos
  vars:
    component_version: "{{ component.version | default(rhos_default_version) }}"
    component_version_director: "{{ (component_version|int in [7, 8, 9]) | ternary(component_version + '-director', '') }}"
  become: yes
  shell: |
    {{ rhos_release_bin }} -x
    {{ rhos_release_bin }} {{ component_version }} {{ component_version_director }}
    yum-config-manager \
      --enable rhelosp-{{ component_version }}.0-unittest \
      --enable rhelosp-{{ component_version }}.0-test-deps \
      >> /var/log/yum.log
  changed_when: true
