# Dependencies with explicit versions are provided by the copr repository.
# Hash any line that is trying to install pip dependency
pep8:

    rpm_deps: [
        python-pbr-0.11.0,
        python2-bashate-0.3.2,
        pyflakes-0.8.1,
        python-mccabe-0.2.1,
        python-flake8-2.1.0
    ]

    remove_rpm: []

    run:
        /usr/bin/sed -i.bak 's/^install_command/#&/' tox.ini;
        /usr/bin/sed -i.bak '/whitelist_externals = bash/a\ flake8\n\ bashate' tox.ini;
        export PBR_VERSION=`awk '/version = / {print $3; exit}' setup.cfg`;
        tox --sitepackages -v -e pep8 2>&1 | tee ../logs/testrun.log


unittest:

    rpm_deps: [
        python-keystone,
        python-testrepository,
        python-testscenarios-0.4,
        python-oslotest,
        python-os-testr-0.8.0,
        python-waitress-0.8.9,
        python-html5lib,
        python-beautifulsoup4-4.3.2,
        python-webtest-2.0.19,
        python-pymongo
    ]

    remove_rpm: [
        python-keystone
    ]

    run:
        /usr/bin/sed -i.bak 's/^install_command/#&/' tox.ini;
        /usr/bin/sed -i.bak '/whitelist_externals = bash/a\ flake8\n\ bashate' tox.ini;
        export PBR_VERSION=`awk '/version = / {print $3; exit}' setup.cfg`;
        tox --sitepackages -v -e py27 2>&1 | tee ../logs/testrun.log


# Tempest target
tempest:
     rpm_deps: []
     remove_rpm: []
     run: ""


# Common rpm deps needed for all tester types (pep8 / unittest)
#
rpm_deps: [
    git,
    python-tox-1.8.1,
    python-virtualenv-1.11.6,
    python-pep8-1.5.7,
    "{{ hostvars[inventory_hostname][tester.component.tox_target]['rpm_deps'] }}"
]


# The rpms that shouldn't be installed when running tests
remove_rpm: [
    "{{ hostvars[inventory_hostname][tester.component.tox_target]['remove_rpm'] }}"
]


keystone_virt_run_config:

  run: >
      set -o pipefail;
      rpm -qa | sort > ../logs/installed-rpms.log;
      truncate --size 0 requirements.txt;
      truncate --size 0 test-requirements.txt;
      {{ hostvars[inventory_hostname][tester.component.tox_target]['run'] }}


# NOTE: This is the main section. It must exist.
test_config:
  virt:
    RedHat-7:
      setup:
        install: "{{rpm_deps}}"
        remove: "{{remove_rpm}}"
      run: "{{keystone_virt_run_config.run}}"
