### This file is used by cinder component jobs
### The jobs can be found on rhos Jenkins: https://rhos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/component-tests

# Testers. Each tester specifies RPMs to install, RPMs to remove and a set of commands that include the invocation of the tester.
pep8:
    rpm_deps: [ pyflakes, python-flake8, python-hacking ]
    remove_rpm: [ python-cinder ]
    run: tox --sitepackages -v -e pep8 2>&1 | tee ../logs/testrun.log;

unittest:
    rpm_deps: [ python-cliff, python-requests-mock, python-webtest ]
    remove_rpm: [ python-cinder ]
    run: >
       tox --sitepackages -v -e py27 2>&1 | tee ../logs/testrun.log;


# Tempest target
tempest:
   rpm_deps: []
   remove_rpm: []
   run: ""

# hostvars[inventory_hostname] is a special ansible variable to get all host's facts
# tester.component.tox_target can be one of the following: [unittest, pep8, dsvm-functional, api]

# Common rpm deps needed for all tester types
rpm_deps: [
  git,
  openstack-cinder,
  python-tox,
  gcc,
  python-devel,
  python-pip,
  python-pbr,
  python-oslo-vmware,
  python-testresources,
  python-testscenarios,

  python-testtools-1.1.0,
  python-babel-1.3,
  python-coverage,
  python-psycopg2,
  MySQL-python,
  python-testrepository,
  python-mock,
  python-mox,
  python-oslotest,
  python-tempest-lib,
  python-oslo-sphinx,
  python-fixtures,
  python-ddt,
  python-subunit,
  python-pep8,
  "{{ hostvars[inventory_hostname][tester.component.tox_target]['rpm_deps'] }}"
]

# The rpms that shouldn't be installed on system, when running tests
remove_rpm: [ "{{ hostvars[inventory_hostname][tester.component.tox_target]['remove_rpm'] }}" ]

# Common pre-run steps used by all tester types
cinder_virt_run_config:
  run: >
    set -o pipefail;
    rpm -qa | sort > ../logs/installed-rpms.log;
    truncate --size 0 requirements.txt;
    truncate --size 0 test-requirements.txt;

    {{ hostvars[inventory_hostname][tester.component.tox_target]['run'] }}


# NOTE: This is the main section. It must exist.
test_config:
  virt:
    RedHat-7:
      setup:
        install: "{{ rpm_deps }}"
        remove: "{{ remove_rpm }}"
      run: "{{ cinder_virt_run_config.run }}"
