- name: Install MariaDB RPM package
  become: yes
  yum:
    name: "{{ db_packages }}"
    state: present

- name: Start mariadb service
  become: yes
  service:
    name: mariadb
    state: started
    enabled: true

- name: Update MariaDB root password
  become: yes
  mysql_user:
    host: "{{ item }}"
    name: root
    password: '{{ db_root_password }}'
    priv: '*.*:ALL,GRANT'
  with_items:
    - '{{ ansible_hostname }}'
    - '127.0.0.1'
    - '::1'
    - 'localhost'

- name: Set config file
  become: yes
  template:
    src: octario_mycnf.j2
    dest: /etc/my.cnf.d/octario_my.cnf
    owner: root
    mode: 0600

- name: Restart MariaDB service
  become: yes
  service:
    name: mariadb
    state: restarted

- name: Create '{{ db_name }}' database
  mysql_db:
    login_user: root
    login_password: '{{ db_root_password }}'
    name: '{{ db_name }}'
    state: present
  when: db_name is defined

- name: Create MariaDB '{{ db_username }}' user and grant privs
  mysql_user:
    login_user: root
    login_password: '{{ db_root_password }}'
    name: '{{ db_username }}'
    password: '{{ db_username }}'
    priv: '*.*:ALL,GRANT'
    state: present
  when: db_username is defined
