# This file handles everything related to packaging.

- name: disable any repos specified
  sudo: yes
  shell: yum-config-manager --disable {{ item }}
  with_items: "{{ component_config.setup.disable_repos | default([]) }}"
  when: component_config.setup | default(false) and component_config.setup.disable_repos | default(false)

- name: enable any additional repos to be used
  sudo: yes
  shell: yum-config-manager --enable {{ item }}
  with_items: "{{ component_config.setup.enable_repos | default([]) }}"
  when: component_config.setup | default(false) and component_config.setup.enable_repos | default(false)

- name: Print summary of all the repositories enabled on the host
  shell: "{{ yum_bin }} repolist all"

- name: Install test dependencies RPMs needed to run the tests
  become: yes
  become_method: sudo
  yum: pkg="{{ item }}" state=latest
  with_items: "{{ component_config.setup.install | default([]) }}"
  when: component_config.setup | default(false) and component_config.setup.install | default(false)

- name: Remove unwanted rpms
  become: yes
  become_method: sudo
  yum: pkg="{{ item }}" state=absent
  with_items: "{{ component_config.setup.remove | default([]) }}"
  when: component_config.setup | default(false) and component_config.setup.remove | default(false)

- name: Install packages needed for converting and collecting the logs
  become: yes
  become_method: sudo
  yum: name="{{ logs_packages }}" state=present
