rhos_default_version: 9
tempest_run_dir: '{{ ansible_env.HOME }}/tempest'
overcloud_venv: '{{ tempest_run_dir }}/.venv'
tempest_venv_activate: |
    {% if tempest_install_type == 'git' %}
    if [[ -d '{{ overcloud_venv }}' ]]; then
      source '{{ overcloud_venv}}/bin/activate'
    fi
    {% endif %}
