rhos_default_version: 9
tempest_run_dir: '{{ ansible_env.HOME }}/tempest'
overcloud_venv: '{{ tempest_run_dir }}/.venv'
tempest_venv_activate: |
    {% if tempest_install_type == 'git' %}
    if [[ -d '{{ overcloud_venv }}' ]]; then
      set +u
      source '{{ overcloud_venv}}/bin/activate'
      set -u
    fi
    {% endif %}
# Once virtualenv fixes bugs below we can remove the set +u/-u
# https://github.com/pypa/virtualenv/issues/1029
# https://github.com/pypa/virtualenv/issues/1029