---
# Notes:
# - PEP8 is ignored because it's not producing subunit streams
# - Test results converted into Junit XML since this is a common format published by most of the CI systems (e.g. Jenkins).

- name: Install packages required for converting and collecting the logs
  become: yes
  yum:
      name: "{{ logs_packages }}"
      state: present

- name: "Set destination log directory path"
  set_fact:
      destination_log_folder: "{{ lookup('env', 'PWD') }}"

- name: Find *.log and *.tar.gz files in the common log directories
  find:
      paths: "{{ ansible_env.HOME }}"
      patterns: "*.log,*.tar.gz"
      file_type: file
      recurse: yes
      age: "-1d"
  register: found_log_files

- name: Fetch log files from the common log directories
  fetch:
      src: "{{ item.path }}"
      dest: "{{ destination_log_folder }}"
  with_items: "{{ found_log_files.files | default([]) }}"

- name: Run pre-collect commands
  shell: |
      export PATH=$PATH:/usr/sbin
      set -euo pipefail
      {{ test.pre.commands }}
  args:
      chdir: "{{ ansible_env.HOME }}"
      executable: "{{ default_shell }}"
  changed_when: false
  when: test.pre is defined
  ignore_errors: true

- name: Fetch common files
  become: yes
  fetch:
      fail_on_missing=no
      src: "{{ item }}"
      dest: "{{ destination_log_folder }}"
  with_items: "{{ common_fetch_list }}"

- name: Copy test results to convert them into junit xml format
  shell: |
      find '{{ ansible_env.HOME }}/*/.testrepository/' -regex '.*/[0-9]+' \
      | while read name; do cat "$name"; done \
      > 'results.subunit'
  ignore_errors: true
  when: convert_fetch_logs | default(false)

- name: Convert test results into Junit XML
  shell: >
      cat results.subunit | subunit-1to2 > results.subunit2;
      cat results.subunit2 | subunit2junitxml > tests_results.xml
  args:
      chdir: "{{ ansible_env.HOME }}"
  ignore_errors: true
  when: convert_fetch_logs | default(false)

- name: Fetch converted test results from remote host
  fetch:
      src: "{{ ansible_env.HOME }}/tests_results.xml"
      dest: "{{ destination_log_folder }}/tests_results.xml"
      flatr: yes
  ignore_errors: true
  no_log: true
