---
# This file handles converting and collecting logs

# Notes:
# - PEP8 is ignored because it's not producing subunit streams
# - Test results converted into Junit XML since this is a common format published by most of the CI systems (e.g Jenkins).
# - 'Pass or Fail' is included in 'collect_logs' role since it should be the last task in the last role, so it can collect logs before Ansible stops running.
# - Collect logs rc ignored, since the command can fail although results were onvereted.

- name: "Set component_path"
  set_fact:
    component_path: "{{ ansible_env.HOME }}/{{ component.name }}"

- name: "Set destination log directory path"
  set_fact:
    destination_log_folder: "{{ lookup('env', 'PWD') }}"

- name: "Prepend component_path to common log directories"
  set_fact:
    component_log_paths="{{ component_path }}/{{ common_log_directories | join(',' + component_path + '/')}}"

- name: Find *.log and *.tar.gz files in the common log directories
  find:
    paths: "{{ component_log_paths.split(',') }}"
    patterns: "*.log,*.tar.gz"
    file_type: file
    recurse: yes
    age: "-1d"
  register: log_files_common
  no_log: true

- name: Fetch log files from the common log directories
  fetch:
    src="{{ item.path }}"
    dest="{{ destination_log_folder }}"
  with_items: "{{ log_files_common.files | default([]) }}"
  no_log: true

- name: Run pre-collect commands (component specific)
  shell: |
      export PATH=$PATH:/usr/sbin
      set -euo pipefail
      {{ component_config.archive_run }}
  args:
      chdir: "{{ ansible_env.HOME }}/{{ component.name }}"
      executable: "{{ default_shell }}"
  changed_when: false
  when: component_config.archive_run is defined
  ignore_errors: true

# due to previous ansible fetch module config, the archive parameter is 
# optional, not failing the task if source is missing. This was needed as
# we have lots of existing jobs that list files that are not always produced
# by current tester(s). 
- name: Fetch files that mentioned in component configuration archive section
  fetch:
    src: "{{ component_path }}/{{ item }}"
    dest: "{{ destination_log_folder }}"
    fail_on_missing: no
  with_items: "{{ component_config.archive | default([]) }}"

- name: Fetch common files
  become: yes
  fetch:
    src="{{ item }}"
    dest="{{ destination_log_folder }}"
    fail_on_missing=no
  with_items: "{{ common_fetch_list }}"

# This task should fail if:
# - no tests results files are found (find)
# - subunit conversion(s) fails
- name: Combine test results and convert them into junit xml format
  shell: |
    set -exo pipefail
    find '{{ component_path }}' -regextype posix-extended -regex '.*/\.(testrepository|stestr).*/[0-9]+' \
    | xargs cat \
    | tee '{{ component_path }}/results.subunit' \
    | subunit-1to2 \
    | tee results.subunit2 \
    | subunit2junitxml > {{ component_path }}/tests_results.xml
  when: tester.component.tox_target != "pep8" and convert_fetch_logs | default(false)

- name: Fetch converted test results from remote host
  fetch:
    src="{{ ansible_env.HOME }}/{{ component.name }}/tests_results.xml"
    dest="{{ destination_log_folder }}/tests_results.xml"
    flat=yes
  when: tester.component.tox_target != "pep8" and convert_fetch_logs | default(false)

- name: Pass or Fail execution based on test results
  fail: msg="The test run failed"
  when: test_run.rc != 0
