---
- name: Run API tests
  hosts: tester
  vars:
    tester:
      component:
          tox_target: api
  roles:
      - { role: setup_repos }
      - { role: setup_environment }
      - { role: run_tests, tester: api }
