- name: Run Octario - Dsvm-Functional tests
  hosts: tester
  vars:
    tester:
      component:
        tox_target: dsvm-functional
  roles:
    - { role: setup_repos }
    - { role: setup_environment }
    - { role: patch_rpm, when: lookup('env', 'GERRIT_REFSPEC') }
    - { role: install_packages }
    - { role: run_tests }
    - { role: collect_logs }
