---
- name: Run functional tests
  hosts: tester
  vars:
    tester:
      component:
          tox_target: functional
  roles:
      - { role: setup_repos }
      - { role: setup_environment }
      - { role: run_tests }
