- name: Run Octario - Functional (Python 3) tests
  hosts: tester
  vars:
    tester:
      component:
        tox_target: functional-py35
  tasks:
    - block:

      - name: "role: setup_repos"
        include_role:
          name: setup_repos

      - name: "role: setup_environment"
        include_role:
          name: setup_environment

      - name: "role: install_packages"
        include_role:
          name: install_packages

      - name: "role: run_tests"
        include_role:
          name: run_tests

      always:
        - name: "role: collect_logs"
          include_role:
            name: collect_logs
