- name: Run Octario - Functional (Python 3) tests
  hosts: tester
  vars:
    tester:
      component:
        tox_target: functional-py35
  roles:
    - { role: setup_repos }
    - { role: setup_environment }
    - { role: install_packages }
    - { role: run_tests }
