- name: Run Octario - Patching RPMs
  hosts: tester
  vars:
    ansible_ssh_user: cloud-user
    tester:
      component:
        tox_target: none
  roles:
    - { role: setup_environment }
    - { role: patch_rpm }
