- name: Run Octario - Patching RPMs
  hosts: openstack_nodes 
  vars:
    ansible_ssh_user: cloud-user
    tester:
      component:
        tox_target: tempest
  roles:
    - { role: setup_repos }
    - { role: setup_environment }
    - { role: patch_rpm }
