# Run Robot tests based on the chosen suite
# ----------------------------------
- name: Run Octario - Robot Framework
  vars:
    ansible_ssh_user: cloud-user
  hosts: tester
  roles:
    - { role: robot }
