# Run Robot tests based on the chosen suite
# ----------------------------------
- name: Run Octario - Robot Framework
  vars:
    ansible_ssh_user: cloud-user
    robot_tests_suite: 'test/csit/suites/netvirt/Openstack_Neutron'
  hosts: tester
  roles:
    - { role: robot }
