---
- name: Run scenario tests
  hosts: tester
  vars:
    tester:
      component:
          tox_target: scenario
  roles:
      - { role: setup_repos }
      - { role: setup_environment }
      - { role: install_packages }
      - { role: run_tests }
