- name: Run Octario - Scenario tests ( in component repo )
  hosts: tester
  vars:
    tester:
      component:
        tox_target: scenario
  tasks:
    - block:

      - name: "role: patch_rpm"
        include_role:
          name: patch_rpm

      - name: "role: setup_repos"
        include_role:
          name: setup_repos

      - name: "role: setup_environment"
        include_role:
          name: setup_environment

      - name: "role: install_packages"
        include_role:
          name: install_packages

      - name: "role: run_tests"
        include_role:
          name: run_tests

      always:

        - name: "role: collect_logs"
          include_role:
            name: collect_logs
