# Run Tempest tests and install it from git
# -----------------------------------------
- name: Run Octario - Tempest
  hosts: tester
  vars:
    tester:
      component:
        tox_target: tempest
    tempest_install_type: "{% if lookup('env','RHOS_VERSION')|int < 7 %}git{% else %}rpm{% endif %}"
  roles:
    - { role: setup_repos }
    - { role: setup_environment }
    - { role: tempest/setup }
    - { role: tempest/run }
