# Run Tempest tests and install it from git
# -----------------------------------------
- name: Run Octario - Tempest
  hosts: tester
  vars:
    tester:
      component:
        tox_target: tempest
    tempest_install_type: git
  roles:
    - { role: setup_environment }
    - { role: setup_tempest }
    - { role: run_tempest }
