# Run Tempest tests and install it from RPM
# NOTE: use this playbook for all branches starting from rhos7
# ------------------------------------------------------------
- name: Run Octario - Tempest
  hosts: tester
  vars:
    tester:
      component:
        tox_target: tempest
    tempest_install_type: rpm
  roles:
    - { role: setup_repos }
    - { role: setup_environment }
    - { role: tempest/setup }
    - { role: tempest/run }
